=== EnderTunes/funnybunnybot/old/config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "token",
    "owner",
    "prefixes"
  ],
  "additionalProperties": false,
  "properties": {
    "token": {
      "type": "string"
    },
    "owner": {
      "type": "string",
      "pattern": "^[0-9]+$"
    },
    "prefixes": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 1
      }
    },
    "adminRole": {
      "type": "string",
      "default": null
    },
    "modRole": {
      "type": "string",
      "default": null
    },
    "privateChannels": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9]+$"
      },
      "default": []
    },
    "noLogServers": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9]+$"
      },
      "default": []
    },
    "noLogChannels": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[0-9]+$"
      },
      "default": []
    },
    "allowCustomColors": {
      "type": "boolean",
      "default": false
    },
    "minecraft": {
      "type": "object",
      "properties": {
        "ip": {
          "type": "string"
        },
        "port": {
          "type": "integer"
        }
      },
      "default": null,
      "additionalProperties": false
    },
    "mumble": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "apiKey": {
          "type": "string"
        }
      },
      "default": null,
      "additionalProperties": false
    },
    "starbound": {
      "type": "object",
      "properties": {
        "statusImage": {
          "type": "string",
          "format": "url"
        }
      },
      "default": null,
      "additionalProperties": false
    },
    "7d": {
      "type": "object",
      "properties": {
        "ip": {
          "type": "string"
        },
        "telnetPort": {
          "type": "integer"
        },
        "telnetPass": {
          "type": "string"
        }
      },
      "default": null,
      "additionalProperties": false
    },
    "userAliases": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[0-9]+$": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "default": {}
    },
    "timezones": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        ".+": {
          "type": "string",
          "format": "IANATimeZone"
        }
      }
    },
    "comic": {
      "properties": {
        "channel": {
          "type": "string",
          "pattern": "^[0-9]+$"
        },
        "users": {
          "type": "object",
          "additionalProperties": false,
          "patternProperties": {
            "^[0-9]+$": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "default": null,
      "additionalProperties": false
    }
  }
}

=== EnderTunes/funnybunnybot/old/config_example.json
{
  "token": "your_bot_token",
  "owner": "your_discord_id",
  "prefixes": [
    "/",
    "!"
  ],
  "adminRole": "some_role_id",
  "modRole": "some_role_id",
  "privateChannels": [],
  "noLogServers": [],
  "noLogChannels": [],
  "allowCustomColors": true,
  "minecraft": {
    "ip": "123.123.123.123",
    "port": 27015
  },
  "mumble": {
    "email": "cooldude@example.com",
    "apiKey": "your_commandchannel_mumble_api_key"
  },
  "starbound": {
    "statusImage": "https://clanforge.multiplay.co.uk/"
  },
  "7d": {
    "ip": "123.123.123.123",
    "telnetPort": 25436,
    "telnetPass": "rosebud"
  },
  "userAliases": {
    "some_user_id": ["joe", "joey"]
  },
  "timezones": {
    "Eastern": "America/New_York",
    "New Zealand": "Pacific/Auckland"
  },
  "comic": {
    "channel": "busy_channel_id",
    "users": {
      "user_id": "user_name"
    }
  }
}
